#
# Copyright (c) 2019-2021 P3TERX <https://p3terx.com>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#
# https://github.com/P3TERX/Actions-OpenWrt
# File: .github/workflows/update-checker.yml
# Description: Source code update checker
#

name: OpenWrt Update Checker

on:
  workflow_dispatch:
    inputs:
      repository:
        description: "Repository name with owner."
        required: true
        default: "coolsnowwolf/lede"
      ref:
        description: "The branch, tag or SHA to checkout."
        required: true
        default: "master"
  schedule:
    - cron: 0 0 ? * FRI

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          path: openwrt
          repository: ${{ github.event.inputs.repository }}
          ref: ${{ github.event.inputs.ref }}

      - name: Get Commit Hash
        id: getHash
        run: |
          cd openwrt
          echo $(git rev-parse HEAD)
          echo "::set-output name=commitHash::$(git rev-parse HEAD)"

      - name: Compare Commit Hash
        id: cacheHash
        uses: actions/cache@v2
        with:
          path: .commitHash
          key: HEAD-${{ steps.getHash.outputs.commitHash }}

      - name: Save New Commit Hash
        if: steps.cacheHash.outputs.cache-hit != 'true'
        run: |
          echo ${{ steps.getHash.outputs.commitHash }} | tee .commitHash

      - name: Trigger build
        if: steps.cacheHash.outputs.cache-hit != 'true'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
          event-type: OpenWrt

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 2
